language: python

python:
  - "3.6"

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.6
  exclude:
    - os: osx
      language: generic
      env: TOXENV=py36    
    
sudo: required

services:
  - docker
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_install:
  - docker pull gcc:4.9
  - docker pull python:latest
  - docker pull java:latest
  - tests/SC/clone.sh 100 tests/SC/myapp.cpp tests/SC/usn

install: 
  - pip3 install -r requirements.txt
  - pip3 install -e .

script: 
  - python3 dbCreator.py
  - pytest tests/test_c.py
  - pytest tests/test_cpp.py
  - pytest tests/test_python2.py
  - pytest tests/test_python.py
  - pytest tests/test_java.py
  - pytest tests/test_basic.py
  - pytest tests/test_basic_50.py
  - pytest tests/test_basic_100.py
  - pytest tests/test_student_APIs.py
  - pytest tests/test_teacher_APIs.py

