language: python

python:
  - "3.6"

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.6
  exclude:
    - os: osx
      language: generic
      env: TOXENV=py36    
    
sudo: required

services:
  - docker

before_install:
  - docker pull gcc:4.9
  - tests/SC/clone.sh 100 tests/SC/myapp.cpp tests/SC/usn

install: 
  - pip3 install -r requirements.txt
  - pip3 install -e .

script: 
  - pytest tests/test_basic.py
  - pytest tests/test_basic_50.py
  - pytest tests/test_basic_100.py
  - pytest tests/test_server_simulation.py

