language: python

python:
  - "3.6"

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.6
  exclude:
    - os: osx
      language: generic
      env: TOXENV=py36    
    
sudo: required

services:
  - docker
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_install:
  - docker pull gcc:4.9
  - docker pull python:latest
  - docker pull java:latest
  - tests/SC/clone.sh 100 tests/SC/myapp.cpp tests/SC/usn

install: 
  - pip3 install -r requirements.txt
  - pip3 install -e .

before_script:
  - echo "Create Test Database..."
  - mysql -e 'CREATE DATABASE your_database_test;'
  - echo "Reset mysql root password..."
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - echo "Installing MySQL 5.7..."
  - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
  - wget http://dev.mysql.com/get/mysql-apt-config_0.8.1-1_all.deb
  - sudo DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.1-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q --force-yes -o Dpkg::Options::=--force-confnew mysql-server
  - sudo mysql_upgrade --force

script: 
  - pytest tests/test_c.py
  - pytest tests/test_cpp.py
  - pytest tests/test_python2.py
  - pytest tests/test_python.py
  - pytest tests/test_java.py
  - pytest tests/test_basic.py
  - pytest tests/test_basic_50.py
  - pytest tests/test_basic_100.py
  - pytest tests/test_student_APIs.py
  - pytest tests/test_teacher_APIs.py

